# Generated by Django 5.1 on 2025-06-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0001_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='comuna',
            field=models.CharField(default='', max_length=100, verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='direccion',
            field=models.CharField(default='', max_length=200, verbose_name='Dirección Física'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='nombre_encargado',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre del Encargado'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='region',
            field=models.CharField(default='', max_length=100, verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='rut',
            field=models.CharField(default='', max_length=20, verbose_name='RUT o Identificación Tributaria'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='telefono',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono de Contacto'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='tipo_giro',
            field=models.CharField(default='', max_length=100, verbose_name='Tipo de Giro'),
        ),
    ]
