# Generated by Django 5.1 on 2025-06-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0003_alter_organizacion_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='db_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Base de Datos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cambio_password_requerido',
            field=models.BooleanField(default=False, verbose_name='Cambio de Contraseña Requerido'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_admin',
            field=models.BooleanField(default=False, verbose_name='Es Administrador'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password_temporal',
            field=models.BooleanField(default=False, verbose_name='Contraseña Temporal'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Login'),
        ),
    ]
